import crypto from 'crypto';
import axios from 'axios';

// PhonePe Sandbox/Test credentials as defaults, replaced by env variables in production
const MERCHANT_ID = process.env.PHONEPE_MERCHANT_ID || 'PGTESTPAYUAT';
const SALT_KEY = process.env.PHONEPE_SALT_KEY || '099eb0cd-02cf-4e2a-8aca-3e6c6aff0399';
const SALT_INDEX = process.env.PHONEPE_SALT_INDEX || '1';

const PHONEPE_HOST = process.env.NODE_ENV === 'production' 
  ? 'https://api.phonepe.com/apis/hermes' 
  : 'https://api-preprod.phonepe.com/apis/pg-sandbox';

/**
 * Initiate PhonePe payment session and generate redirect Pay Page URL
 * @param {number} amount - Total amount in INR
 * @param {string} merchantTransactionId - Unique transaction ID generated by backend
 * @param {string} redirectUrl - Frontend page to redirect user after completion (e.g. /dashboard)
 * @param {string} callbackUrl - Backend webhook endpoint to confirm transaction status
 * @returns {Promise<Object>} Object containing redirect URL and merchantTransactionId
 */
export const initiatePhonePePayment = async (amount, merchantTransactionId, redirectUrl, callbackUrl) => {
  const payload = {
    merchantId: MERCHANT_ID,
    merchantTransactionId,
    merchantUserId: 'MUID' + Date.now(),
    amount: Math.round(amount * 100), // Convert to paise
    redirectUrl,
    redirectMode: 'REDIRECT',
    callbackUrl,
    paymentInstrument: {
      type: 'PAY_PAGE'
    }
  };

  const payloadString = JSON.stringify(payload);
  const base64Payload = Buffer.from(payloadString).toString('base64');
  
  // Signature calculation: SHA256(Base64Payload + "/pg/v1/pay" + SaltKey) + "###" + SaltIndex
  const stringToSign = base64Payload + '/pg/v1/pay' + SALT_KEY;
  const sha256 = crypto.createHash('sha256').update(stringToSign).digest('hex');
  const xVerify = sha256 + '###' + SALT_INDEX;

  try {
    const response = await axios.post(`${PHONEPE_HOST}/pg/v1/pay`, {
      request: base64Payload
    }, {
      headers: {
        'Content-Type': 'application/json',
        'X-VERIFY': xVerify,
        'accept': 'application/json'
      }
    });

    if (response.data && response.data.success) {
      return {
        success: true,
        redirectUrl: response.data.data.instrumentResponse.redirectInfo.url,
        transactionId: response.data.data.merchantTransactionId
      };
    } else {
      throw new Error(response.data.message || 'Payment initiation failed');
    }
  } catch (error) {
    console.error('PhonePe API Error:', error.response ? error.response.data : error.message);
    throw new Error(error.response?.data?.message || error.message);
  }
};

/**
 * Verify callback signature received from PhonePe webhook or redirect handler
 * @param {string} base64Response - Request body from PhonePe containing response payload
 * @param {string} headerXVerify - Header signature checksum to compare against
 * @returns {boolean} True if checksum is verified successfully
 */
export const verifyPhonePeChecksum = (base64Response, headerXVerify) => {
  const stringToSign = base64Response + SALT_KEY;
  const sha256 = crypto.createHash('sha256').update(stringToSign).digest('hex');
  const computedSignature = sha256 + '###' + SALT_INDEX;
  
  return computedSignature === headerXVerify;
};
